---
- name: Download Tomcat10 from apache.tomcat.org
  hosts: webservers
  vars: 
    download_url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
  tasks:
   
   - name: Create the group
     become: yes
     group: 
      name: tomcat
      state: present
   - name: Installing Java(JDK) (if not present)
     apt:
      name: openjdk-11-jre-headless
      state: present
      update_cache: yes
   - name: Create the user
     become: yes
     user:
        name: tomcat
        state: present
   - name: Create a Directory /opt/tomcat
     become: yes
     file:
       path: /opt/tomcat
       state: directory
       mode: 0775
       owner: tomcat
       group: tomcat
   - name: Download Tomcat using unarchive
     become: yes
     unarchive:
       src: "{{download_url}}"
       dest: /opt/tomcat
       mode: 0755
       remote_src: yes
       extra_opts: [--strip-components=1]
       group: tomcat
       owner: tomcat
   - name: Creating a service file
     become: yes
     copy:
      dest: /etc/systemd/system/tomcat.service 
      content: |          
          [Unit]
          Description=Tomcat
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
          Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          RestartSec=10
          Restart=always

          [Install]   
          WantedBy=multi-user.target  
        
  
   - name: Task 6 Reload the SystemD to re-read configurations
     become: yes
     systemd:
       daemon-reload: yes
   - name: Task 7 Start service tomcat, if not started
     become: yes
     systemd:
       name: tomcat
       state: started
       enabled: no
   - name: Task 8 Allow all access to tcp port 8080
     ufw:
       rule: allow
       port: '8080'
       proto: tcp
       state: enabled