---
- name: user creation playbook for webservers
  hosts: webservers
  tasks:
    - name: Add the user 'raj' with a specific uid and a primary group of 'sudo'
      user:
         name: raj
         comment: Raj goud
         uid: 10777
         group: sudo 

    - name: multifile creation in allservers playbook
      hosts: allservers
      tasks:
        - name: multiple file creation using list
          file:
            path: "/tmp/{{item}}"
            state: touch
          with_items:
            - r1.txt
            - r2.txt
            - r3.txt

...

